output_dir: ./output/tldr/

gradient_checkpointing: true
model_and_preference_share_basemodel: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 20
learning_rate: 1.0e-7

max_length: 2048
generate_temperature: 1.0
forward_temperature: 1.0
beta: 0.04

bf16: true
dataset_num_proc: 1
num_astar: 1
torch_empty_cache_steps: 50
num_train_epochs: 1

eval_steps: 500
eval_strategy: "no"
save_strategy: "steps"
save_steps: 1000
logging_steps: 50
push_to_hub: false

is_bt_model: true
preference_model_id: cleanrl/EleutherAI_pythia-6.9b-deduped__reward__tldr
preference_model_kwargs:
  indifferent: false
  random: false
  reverse: false

ratio_processing: clip
clipbound: 2.5
max_grad_norm: 0.25

loss1_only: false
loss2_only: false